name: Prefect CI/CD Pipeline with Prefect Cloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-prefect-workflows:
    runs-on: ubuntu-latest

    env:
      TZ: "Asia/Kolkata"  # Set the time zone to New Delhi/Kolkata (UTC+5:30)

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set current date and time in Asia/Kolkata timezone
      id: set_datetime
      run: |
        export TZ="Asia/Kolkata"
        echo "Current date and time in Asia/Kolkata: $(date +'%Y-%m-%d %H:%M:%S')"
        echo "CURRENT_DATE_TIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Authenticate with Prefect Cloud
      env:
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      run: |
        prefect cloud login --key $PREFECT_API_KEY --workspace 'shreyas-rao/default'

    - name: Run Prefect deployment on Prefect Cloud
      run: |
        prefect deployment run 'main-flow/covid-ds-workflow'
