name: Prefect CI/CD Pipeline with Prefect Cloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-prefect-workflows:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Authenticate with Prefect Cloud
      env:
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      run: |
        prefect cloud login --key $PREFECT_API_KEY

    - name: Run Prefect deployment on Prefect Cloud
      run: |
        prefect deployment run 'main-flow/covid-ds-workflow'
