name: Prefect CI/CD Pipeline for Data Science Project

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Define a job to set up Python and run Prefect workflows
  run-prefect-workflows:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Start Prefect Orion server in the background
    - name: Start Prefect Orion server
      run: nohup prefect orion start &

    # Step 5: Run the Prefect workflow
    - name: Run Prefect workflow
      run: |
        cd flows
        python workflow_covidex.py
